import { expect, test } from 'claude-code/testing'
import { ROOT, world } from './world.ts'

const TOOL = 'mcp__loose-ends__note_loose_end'
const BAND = { component: 'AbovePrompt', props: { hasSurvey: false, isWorking: false, maxRows: 10, bodyColumns: 100 } as any }
const PANE = { component: 'Pane', requestId: 'loose-ends', props: { title: 'Cuaderno', isFocused: true, bodyColumns: 60, placement: 'dock' } as any }
const T0 = '2026-10-04T09:00:00.000Z'
const it = (id: string, text: string, over = {}) => ({ id, text, category: 'deuda', priority: 'medium', status: 'open', branch: 'main', createdAt: T0, ...over })
const blob = (...items: any[]) => JSON.stringify({ version: 2, items })
const EVIDENCE = 'lo dejo para otro día'
const EVIDENCE_2 = 'y el test lo omito por ahora'
const longAnswer = () => `${'y'.repeat(500)} ${EVIDENCE}. ${EVIDENCE_2}`
const answered = (text: string) => ({ value: { isAnswered: true, text, usage: { input_tokens: 0, output_tokens: 0, cache_read_input_tokens: 0, cache_creation_input_tokens: 0 } } })
// the engine's own drawing: a Text with the message's text, so a test sees what the mod handed it
const drawEngine = (on: any) => on('ui.render', ($: any, e: any) => ({ type: 'Text', children: [e.props?.text ?? 'engine'] }))
const turns = (on: any) => {
  on('turn.start', ($: any, e: any) => ({ turnId: e.turnId }))
  on('turn.complete', ($: any, e: any) => ({ text: e.answer }))
}
const endTurn = ($: any, answer = longAnswer(), turnId = 't') => $.turn.complete({ answer, durationMs: 10, isAborted: false, turnId, reason: 'answer' })
const message = ($: any, text: string, surface = 'desktop') => $.ui.mount({ plugin: 'loose-ends', surface, component: 'AssistantMessage', props: { text, isFirstOfReply: true } as any })
const pane = ($: any, surface = 'desktop') => $.ui.mount({ plugin: 'loose-ends', surface, ...PANE })
const band = ($: any, surface = 'desktop') => $.ui.mount({ plugin: 'loose-ends', surface, ...BAND })
const withCandidate = () => blob(it('c1', 'Comprimir la foto 3', { status: 'candidate', category: 'mejora', evidence: EVIDENCE }), it('a1', 'Tipar drafts'))
const find = (w: any, id: string) => w.saved().find((i: any) => i.id === id)

test('the tool proposes a candidate and tells Claude the person decides', async ($, on) => {
  const w = world(on)
  await w.start($)
  const r = await $.tool.call({ tool: TOOL, text: 'Corregir el envío duplicado de correo', category: 'bug', priority: 'high', evidence: 'lo dejo fuera', file: '/proj/lib/facturas.ts' })
  expect(String(r.result)).toMatch(/^Propuesto como cabo \(\w{8}\): Corregir el envío duplicado de correo\. El usuario lo confirmará\.$/)
  expect(w.saved()[0]).toMatchObject({ status: 'candidate', category: 'bug', priority: 'high', source: 'tool', file: 'lib/facturas.ts', branch: 'main' })
  expect(w.toasts).toEqual([])
})

test('the filter refuses what is not a loose end and says why', async ($, on) => {
  const w = world(on)
  await w.start($)
  const noCategory = await $.tool.call({ tool: TOOL, text: 'Corregir el parser', priority: 'low' })
  expect(noCategory.result).toBe('No se ha propuesto: sin categoría (bug, deuda, test, aviso o mejora).')
  const waiting = await $.tool.call({ tool: TOOL, text: 'Esperar a que termine el CI', category: 'aviso', priority: 'low' })
  expect(String(waiting.result)).toContain('No se ha propuesto: no es trabajo sobre el código')
  await $.tool.call({ tool: TOOL, text: 'Corregir el parser', category: 'bug', priority: 'low' })
  const again = await $.tool.call({ tool: TOOL, text: 'corregir el PARSER', category: 'bug', priority: 'low' })
  expect(again.result).toBe('No se ha propuesto: ya está apuntado.')
  const short = await $.tool.call({ tool: TOOL, text: ' a ', category: 'bug', priority: 'low' })
  expect(String(short.result)).toContain('demasiado corto')
  expect(w.saved()).toHaveLength(1)
  expect(w.logs.some(l => l.includes('candidato rechazado'))).toBe(true)
})

test('concurrent proposals are both saved, each with the branch of its moment', async ($, on) => {
  const w = world(on)
  await w.start($)
  await Promise.all([
    $.tool.call({ tool: TOOL, text: 'Primer cabo suelto', category: 'deuda', priority: 'low' }),
    $.tool.call({ tool: TOOL, text: 'Segundo cabo suelto', category: 'deuda', priority: 'low' }),
  ])
  w.setBranch('feat/x')
  await $.tool.call({ tool: TOOL, text: 'Cabo en la rama', category: 'deuda', priority: 'low' })
  expect(w.saved().map((i: any) => [i.text, i.branch]).sort()).toEqual([['Cabo en la rama', 'feat/x'], ['Primer cabo suelto', 'main'], ['Segundo cabo suelto', 'main']])
})

test('the sweep proposes candidates and closures, and closes nothing by itself', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts'), it('r1', 'Comprobar el CI', { status: 'rejected', closedAt: T0 }), it('w1', 'Candidato que espera', { status: 'candidate' })) } })
  let asked = ''
  on('model.complete', ($: any, e: any) => {
    asked = e.prompt
    return answered(`{"new":[{"text":"Comprimir la foto 3","category":"mejora","priority":"low","evidence":"${EVIDENCE}"}],"resolved":[{"id":"a1","quote":"${EVIDENCE_2}"}]}`)
  })
  turns(on)
  await w.start($)
  await endTurn($)
  await w.clock.settle()
  expect(asked).toContain('a1: Tipar drafts')
  expect(asked).toContain('Por revisar (no los repitas):\n- Candidato que espera')
  expect(asked).toContain('Ejemplos que el usuario rechazó (no propongas nada parecido):\n- Comprobar el CI')
  expect(find(w, 'a1')).toMatchObject({ status: 'open', proposal: { quote: EVIDENCE_2 } })
  expect(w.saved().find((i: any) => i.text === 'Comprimir la foto 3')).toMatchObject({ status: 'candidate', source: 'sweep', category: 'mejora' })
})

test('the last commit made since the turn started goes into the proposal, whatever the command was', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts')) }, head: 'a3f9c21' })
  on('model.complete', () => answered(`{"new":[],"resolved":[{"id":"a1","quote":"${EVIDENCE_2}"}]}`))
  turns(on)
  await w.start($)
  await $.turn.start({ text: 'hola', turnId: 't' })
  await endTurn($)
  await w.clock.settle()
  expect(find(w, 'a1').proposal).toMatchObject({ quote: EVIDENCE_2, commit: 'a3f9c21' })
  expect(w.runs.some(a => a.includes('--since=2026-10-04T10:00:00.000Z'))).toBe(true)
})

test('a turn without a commit leaves the proposal without one', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts')) }, head: 'a3f9c21', headAt: '2026-10-04T09:00:00.000Z' })
  on('model.complete', () => answered(`{"new":[],"resolved":[{"id":"a1","quote":"${EVIDENCE_2}"}]}`))
  turns(on)
  await w.start($)
  await $.turn.start({ text: 'hola', turnId: 't' })
  await endTurn($)
  await w.clock.settle()
  expect(find(w, 'a1').proposal.quote).toBe(EVIDENCE_2)
  expect(find(w, 'a1').proposal.commit).toBeUndefined()
})

test('short answers bring no new items, but an item in progress is still checked', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts')) } })
  let calls = 0
  on('model.complete', () => {
    calls++
    return answered(`{"new":[{"text":"Nuevo cabo","category":"bug","evidence":"${EVIDENCE}"}],"resolved":[{"id":"a1","quote":"${EVIDENCE}"}]}`)
  })
  turns(on)
  await w.start($)
  await endTurn($, `corto: ${EVIDENCE}`)
  await w.clock.settle()
  expect(calls).toBe(0)
  w.setRef(ROOT, blob(it('a1', 'Tipar drafts', { status: 'doing' })))
  await endTurn($, `corto: ${EVIDENCE}`, 't2')
  await w.clock.settle()
  expect(calls).toBe(1)
  expect(w.saved().map((i: any) => i.id)).toEqual(['a1'])
  expect(find(w, 'a1')).toMatchObject({ status: 'doing', proposal: { quote: EVIDENCE } })
})

test('only an answered turn is swept; a broken reply changes nothing', async ($, on) => {
  const w = world(on)
  let calls = 0
  on('model.complete', () => { calls++; return answered('no es json') })
  turns(on)
  await w.start($)
  await $.turn.complete({ answer: longAnswer(), durationMs: 1, isAborted: false, turnId: 't', reason: 'error' })
  await w.clock.settle()
  expect(calls).toBe(0)
  await endTurn($, longAnswer(), 't2')
  await w.clock.settle()
  expect(calls).toBe(1)
  expect(w.saved()).toEqual([])
  expect(w.logs).toContain('loose-ends: barrido con JSON inválido')
})

test('the sweep logs why it could not file a candidate', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts')) } })
  on('model.complete', () => {
    w.setRef(ROOT, '{ roto')
    return answered(`{"new":[{"text":"Comprimir la foto 3","category":"mejora","priority":"low","evidence":"${EVIDENCE}"}],"resolved":[]}`)
  })
  turns(on)
  await w.start($)
  await endTurn($)
  await w.clock.settle()
  expect(w.logs).toContain('loose-ends: no se pudo proponer en /proj (json)')
})

test('the sweep never touches an item the person closed meanwhile', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts')) } })
  on('model.complete', () => {
    w.setRef(ROOT, blob(it('a1', 'Tipar drafts', { status: 'dismissed', closedAt: '2026-10-04T10:00:01.000Z', updatedAt: '2026-10-04T10:00:01.000Z' })))
    return answered(`{"new":[],"resolved":[{"id":"a1","quote":"${EVIDENCE_2}"}]}`)
  })
  turns(on)
  await w.start($)
  await endTurn($)
  await w.clock.settle()
  expect(find(w, 'a1').status).toBe('dismissed')
  expect(find(w, 'a1').proposal).toBeUndefined()
})

test('candidates older than 7 days expire at the end of a turn', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('c1', 'Candidato viejo', { status: 'candidate', createdAt: '2026-09-27T09:00:00.000Z' })) } })
  turns(on)
  await w.start($)
  await endTurn($, 'corto')
  expect(find(w, 'c1').status).toBe('expired')
})

test('a candidate shows as a card under the message that said it, with the sentence in bold', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: withCandidate() } })
  drawEngine(on)
  await w.start($)
  const msg = await message($, `Listo. Eso sí, ${EVIDENCE}.`)
  expect(await msg.find({ type: 'Text', text: `Listo. Eso sí, **${EVIDENCE}**.` })).toBeDefined()
  expect(await msg.find({ type: 'Text', text: 'Cabo candidato · mejora · normal' })).toBeDefined()
  expect(await msg.find({ key: 'tri-save-c1' })).toBeDefined()
  await msg.unmount()
  const other = await message($, 'Otra respuesta sin la frase')
  expect(await other.find({ key: 'tri-save-c1' })).toBeUndefined()
  expect(await other.find({ type: 'Text', text: 'Otra respuesta sin la frase' })).toBeDefined()
  await other.unmount()
})

test('Guardar from the card saves the candidate; Deshacer puts it back', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: withCandidate() } })
  drawEngine(on)
  await w.start($)
  const msg = await message($, `Eso sí, ${EVIDENCE}.`)
  await msg.press({ key: 'tri-save-c1' })
  await w.clock.settle()
  await msg.redraw()
  expect(find(w, 'c1').status).toBe('open')
  expect(await msg.find({ type: 'Text', text: 'Guardado en proj' })).toBeDefined()
  await msg.press({ key: 'tri-undo-c1' })
  await w.clock.settle()
  await msg.redraw()
  expect(find(w, 'c1').status).toBe('candidate')
  expect(await msg.find({ key: 'tri-save-c1' })).toBeDefined()
  await msg.unmount()
})

test('No es un cabo rejects it, and the next sweep learns from it', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: withCandidate() } })
  drawEngine(on)
  let asked = ''
  on('model.complete', ($: any, e: any) => { asked = e.prompt; return answered('{"new":[],"resolved":[]}') })
  turns(on)
  await w.start($)
  const msg = await message($, `Eso sí, ${EVIDENCE}.`)
  await msg.press({ key: 'tri-reject-c1' })
  await w.clock.settle()
  await msg.redraw()
  expect(find(w, 'c1').status).toBe('rejected')
  expect(await msg.find({ type: 'Text', text: 'Descartado. No volveré a proponer cosas así.' })).toBeDefined()
  await msg.unmount()
  await endTurn($)
  await w.clock.settle()
  expect(asked).toContain('Ejemplos que el usuario rechazó (no propongas nada parecido):\n- Comprimir la foto 3')
})

test('Editar on the card changes the text before saving', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: withCandidate() } })
  drawEngine(on)
  await w.start($)
  const msg = await message($, `Eso sí, ${EVIDENCE}.`)
  await msg.press({ key: 'tri-edit-c1' })
  await msg.redraw()
  await msg.input({ key: 'tri-edit-input-c1', text: 'Comprimir las fotos de la galería' })
  await w.clock.settle()
  await msg.redraw()
  expect(find(w, 'c1')).toMatchObject({ text: 'Comprimir las fotos de la galería', status: 'candidate' })
  expect(await msg.find({ key: 'tri-save-c1' })).toBeDefined()
  await msg.unmount()
})

test('a proposed closure: Sí, cerrar keeps the proof and the band offers Deshacer', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Arreglar el envío duplicado', { proposal: { quote: EVIDENCE_2, commit: 'a3f9c21', at: T0 } })) } })
  drawEngine(on)
  await w.start($)
  const msg = await message($, `Listo: ${EVIDENCE_2}.`)
  expect(await msg.find({ type: 'Text', text: '¿Resuelto? · commit a3f9c21' })).toBeDefined()
  await msg.press({ key: 'tri-confirm-a1' })
  await w.clock.settle()
  expect(find(w, 'a1')).toMatchObject({ status: 'done', proof: { quote: EVIDENCE_2, commit: 'a3f9c21' } })
  const term = await band($, 'terminal')
  expect(await term.find({ type: 'Text', text: 'Cerrado: Arreglar el envío duplicado' })).toBeDefined()
  expect(await term.find({ type: 'Text', text: '\\(•ᴗ•)/' })).toBeDefined()
  await term.press({ key: 'undo-close' })
  await w.clock.settle()
  expect(find(w, 'a1')).toMatchObject({ status: 'open', proposal: { quote: EVIDENCE_2 } })
  await term.unmount()
  await msg.unmount()
})

test('Sigue abierto clears the proposal', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Arreglar el envío duplicado', { status: 'doing', proposal: { quote: EVIDENCE_2, at: T0 } })) } })
  drawEngine(on)
  await w.start($)
  const msg = await message($, `Listo: ${EVIDENCE_2}.`)
  await msg.press({ key: 'tri-keep-a1' })
  await w.clock.settle()
  await msg.redraw()
  expect(find(w, 'a1').status).toBe('open')
  expect(find(w, 'a1').proposal).toBeUndefined()
  expect(await msg.find({ type: 'Text', text: 'Sigue abierto.' })).toBeDefined()
  await msg.unmount()
})

test('the band Deshacer puts back what the close started from, and the card forgets its answer', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: withCandidate() } })
  drawEngine(on)
  await w.start($)
  const msg = await message($, `Eso sí, ${EVIDENCE}.`)
  await msg.press({ key: 'tri-save-c1' })
  await w.clock.settle()
  await msg.redraw()
  expect(await msg.find({ key: 'tri-undo-c1' })).toBeDefined()
  const ui = await pane($)
  await ui.press({ key: 'done-c1' })
  await w.clock.settle()
  expect(find(w, 'c1').status).toBe('done')
  await msg.redraw()
  expect(await msg.find({ key: 'tri-undo-c1' })).toBeUndefined()
  const term = await band($, 'terminal')
  await term.press({ key: 'undo-close' })
  await w.clock.settle()
  expect(find(w, 'c1').status).toBe('open')
  await term.unmount()
  await ui.unmount()
  await msg.unmount()
})

test('Hacer after a card answer makes the card forget it, so its Deshacer cannot bring back a stale state', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: withCandidate() } })
  drawEngine(on)
  on('prompt.submit', ($: any, e: any) => ({ text: e.text }))
  await w.start($)
  const msg = await message($, `Eso sí, ${EVIDENCE}.`)
  await msg.press({ key: 'tri-save-c1' })
  await w.clock.settle()
  await msg.redraw()
  expect(await msg.find({ key: 'tri-undo-c1' })).toBeDefined()
  const ui = await pane($)
  await ui.press({ key: 'now-c1' })
  await w.clock.settle()
  expect(find(w, 'c1').status).toBe('doing')
  await msg.redraw()
  expect(await msg.find({ key: 'tri-undo-c1' })).toBeUndefined()
  await ui.unmount()
  await msg.unmount()
})

test('a closure the sweep proposes makes the card forget its answer', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: withCandidate() } })
  drawEngine(on)
  on('model.complete', () => answered(`{"new":[],"resolved":[{"id":"c1","quote":"${EVIDENCE_2}"}]}`))
  turns(on)
  await w.start($)
  const msg = await message($, `Eso sí, ${EVIDENCE}.`)
  await msg.press({ key: 'tri-save-c1' })
  await w.clock.settle()
  await msg.redraw()
  expect(await msg.find({ key: 'tri-undo-c1' })).toBeDefined()
  await endTurn($)
  await w.clock.settle()
  expect(find(w, 'c1').proposal).toMatchObject({ quote: EVIDENCE_2 })
  await msg.redraw()
  expect(await msg.find({ key: 'tri-undo-c1' })).toBeUndefined()
  await msg.unmount()
})

test('a card answer that changed nothing is not remembered', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: withCandidate() } })
  drawEngine(on)
  await w.start($)
  const msg = await message($, `Eso sí, ${EVIDENCE}.`)
  // another session saved the candidate meanwhile
  w.setRef(ROOT, blob(it('c1', 'Comprimir la foto 3', { status: 'open', category: 'mejora', evidence: EVIDENCE }), it('a1', 'Tipar drafts')))
  await msg.press({ key: 'tri-reject-c1' })
  await w.clock.settle()
  await msg.redraw()
  expect(find(w, 'c1').status).toBe('open')
  expect(w.writes).toEqual([])
  expect(await msg.find({ type: 'Text', text: /Descartado/ })).toBeUndefined()
  await msg.unmount()
})

test('pane: Guardar, Hacer starts the item and sends the prompt, Hecho closes it, ↺ reopens it', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: withCandidate() } })
  drawEngine(on)
  let sent = ''
  on('prompt.submit', ($: any, e: any) => { sent = e.text; return { text: e.text } })
  await w.start($)
  const ui = await pane($)
  await ui.press({ key: 'save-c1' })
  await w.clock.settle()
  expect(find(w, 'c1').status).toBe('open')
  await ui.redraw()
  await ui.press({ key: 'now-a1' })
  await w.clock.settle()
  expect(sent).toBe('Resuelve este cabo suelto (a1): Tipar drafts')
  expect(find(w, 'a1').status).toBe('doing')
  await ui.redraw()
  await ui.press({ key: 'done-a1' })
  await w.clock.settle()
  await ui.redraw()
  expect(find(w, 'a1').status).toBe('done')
  await ui.press({ key: 'reopen-a1' })
  await w.clock.settle()
  expect(find(w, 'a1').status).toBe('open')
  await ui.unmount()
})

test('pane: the priority word cycles, editar edits, a hand-written one opens at once, Descartar dismisses', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts')) } })
  drawEngine(on)
  await w.start($)
  const ui = await pane($)
  await ui.press({ key: 'prio-a1' })
  await w.clock.settle()
  expect(find(w, 'a1').priority).toBe('low')
  await ui.redraw()
  await ui.press({ key: 'edit-a1' })
  await ui.redraw()
  await ui.input({ key: 'edit-input-a1', text: 'Tipar los drafts del equipo' })
  await w.clock.settle()
  expect(find(w, 'a1').text).toBe('Tipar los drafts del equipo')
  await ui.redraw()
  await ui.input({ key: 'add-item', text: 'Cabo escrito a mano' })
  await w.clock.settle()
  expect(w.saved().find((i: any) => i.text === 'Cabo escrito a mano')).toMatchObject({ status: 'open', source: 'manual', category: 'mejora' })
  await ui.redraw()
  await ui.press({ key: 'dismiss-a1' })
  await w.clock.settle()
  expect(find(w, 'a1').status).toBe('dismissed')
  await ui.unmount()
})

test('pane: a stale item can be kept fresh', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts', { createdAt: '2026-09-01T00:00:00.000Z' })) } })
  drawEngine(on)
  await w.start($)
  const ui = await pane($)
  expect(await ui.find({ type: 'Text', text: '¿Sigue vigente?' })).toBeDefined()
  await ui.press({ key: 'fresh-a1' })
  await w.clock.settle()
  await ui.redraw()
  expect(find(w, 'a1').updatedAt).toBe('2026-10-04T10:00:00.000Z')
  expect(await ui.find({ type: 'Text', text: '¿Sigue vigente?' })).toBeUndefined()
  await ui.unmount()
})

test('pane: Subir pushes the ref when there are changes to push', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts')) }, remote: { [ROOT]: '' } })
  drawEngine(on)
  await w.start($)
  await w.clock.settle()
  const ui = await pane($)
  expect(await ui.find({ type: 'Text', text: 'Cambios sin subir' })).toBeDefined()
  await ui.press({ key: 'push-now' })
  await w.clock.settle()
  await ui.redraw()
  expect(w.pushes).toEqual([ROOT])
  expect(await ui.find({ type: 'Text', text: 'Al día con origin' })).toBeDefined()
  await ui.unmount()
})

test('pane: a write after Subir shows the changes as unpushed again', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts')) }, remote: { [ROOT]: '' } })
  drawEngine(on)
  await w.start($)
  await w.clock.settle()
  const ui = await pane($)
  await ui.press({ key: 'push-now' })
  await w.clock.settle()
  await ui.redraw()
  expect(await ui.find({ type: 'Text', text: /Al d.a con origin/ })).toBeDefined()
  expect(await ui.find({ key: 'push-now' })).toBeUndefined()
  await ui.press({ key: 'prio-a1' })
  await w.clock.settle()
  await ui.redraw()
  expect(await ui.find({ type: 'Text', text: 'Cambios sin subir' })).toBeDefined()
  expect(await ui.find({ key: 'push-now' })).toBeDefined()
  await ui.unmount()
})

test('pane: the import notice shows after the 0.3 file was imported', async ($, on) => {
  const w = world(on, { '/proj/.claude/loose-ends.json': JSON.stringify({ version: 1, items: [it('q1', 'Docs de jsonld', { status: 'queued', remindedAt: T0 })] }) })
  drawEngine(on)
  await w.start($)
  await w.clock.settle()
  const ui = await pane($)
  expect(await ui.find({ type: 'Text', text: 'Importados 1 cabo de .claude/loose-ends.json. Ya puedes borrar el fichero del repo.' })).toBeDefined()
  expect(await ui.find({ key: 'now-q1' })).toBeDefined()
  await ui.unmount()
})

test('the mobile pane draws, without fields', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: withCandidate() } })
  drawEngine(on)
  await w.start($)
  const ui = await pane($, 'mobile')
  expect(await ui.find({ key: 'save-c1' })).toBeDefined()
  expect(await ui.find({ key: 'add-item' })).toBeUndefined()
  expect(await ui.find({ key: 'edit-a1' })).toBeUndefined()
  await ui.unmount()
})

test('a failing write from a pane button is logged, not thrown', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts')) } })
  drawEngine(on)
  await w.start($)
  await w.clock.settle()
  const ui = await pane($)
  w.flags.failWrites = true
  await ui.press({ key: 'done-a1' })
  await w.clock.settle()
  expect(w.logs).toEqual([expect.stringContaining('falló')])
  await ui.unmount()
})

test('Hacer does not send the prompt when the ref became unreadable', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts')) } })
  drawEngine(on)
  let sent = ''
  on('prompt.submit', ($: any, e: any) => { sent = e.text; return { text: e.text } })
  await w.start($)
  const ui = await pane($)
  w.setRef(ROOT, '{ roto')
  await ui.press({ key: 'now-a1' })
  await w.clock.settle()
  expect(sent).toBe('')
  await ui.unmount()
})

test('band: candidates make Chispa hold a note and the line asks to review', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: withCandidate() } })
  drawEngine(on)
  let opened = ''
  on('ui.open', ($: any, e: any) => { opened = e.id; return { value: { isPlaced: true } } })
  await w.start($)
  const desk = await band($)
  expect(await desk.find({ type: 'Svg' })).toBeDefined()
  expect((await desk.find({ key: 'band-line' }))?.text).toBe('1 por revisar · 1 abierto · [Revisar](file:///loose-ends/ver)')
  await desk.unmount()
  const term = await band($, 'terminal')
  expect(await term.find({ type: 'Text', text: '(•ᴗ•)✎' })).toBeDefined()
  await term.press({ key: 'open-pane' })
  await w.clock.settle()
  expect(opened).toBe('loose-ends')
  await term.unmount()
})

test('band: an urgent item is named and worries Chispa', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Arreglar el login', { priority: 'high' })) } })
  drawEngine(on)
  await w.start($)
  const term = await band($, 'terminal')
  expect(await term.find({ type: 'Text', text: 'Urgente: Arreglar el login' })).toBeDefined()
  expect(await term.find({ type: 'Text', text: '(•_•)!' })).toBeDefined()
  await term.unmount()
})

test('band: Chispa works during a turn, rests after it, and sleeps after 30 min still', async ($, on) => {
  const w = world(on)
  drawEngine(on)
  turns(on)
  await w.start($)
  const term = await band($, 'terminal')
  expect(await term.find({ type: 'Text', text: '(•ᴗ•)' })).toBeDefined()
  expect(await term.find({ key: 'open-pane' })).toBeUndefined()
  await $.turn.start({ text: 'hola', turnId: 't' })
  await term.redraw()
  expect(await term.find({ type: 'Text', text: '(•̀ᴗ•́)⌨' })).toBeDefined()
  await endTurn($, 'corto')
  await term.redraw()
  expect(await term.find({ type: 'Text', text: '(•ᴗ•)' })).toBeDefined()
  await w.clock.advance(30 * 60 * 1000)
  await term.redraw()
  expect(await term.find({ type: 'Text', text: '(-_-)zᶻ' })).toBeDefined()
  await term.unmount()
})

test('the system prompt gets the guide and the first message the live items', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: blob(it('a1', 'Tipar drafts', { priority: 'high' }), it('c1', 'Candidato sin decidir', { status: 'candidate' })) } })
  on('prompt.compose', () => ({ sections: [{ id: 'core', text: 'x', scope: 'shared' }] }))
  on('prompt.context', ($: any, e: any) => ({ blocks: e.blocks }))
  await w.start($)
  const composed = await $.prompt.compose({ model: 'm', promptModel: 'm', surfaces: ['desktop'], tools: [], outputStyle: null, traits: [] })
  expect(composed.sections.at(-1)).toMatchObject({ id: 'loose-ends:guide', scope: 'session' })
  const r = await $.prompt.context({ blocks: [] })
  expect(r.blocks.at(-1).text).toContain('- [high] Tipar drafts (a1, rama main)')
  expect(r.blocks.at(-1).text).not.toContain('Candidato sin decidir')
})

test('turn end refreshes the items from a ref another session moved', async ($, on) => {
  const w = world(on)
  turns(on)
  on('prompt.context', ($: any, e: any) => ({ blocks: e.blocks }))
  await w.start($)
  w.setRef(ROOT, blob(it('h1', 'Escrito en otra sesión', { priority: 'high' })))
  await endTurn($, 'corto')
  const r = await $.prompt.context({ blocks: [] })
  expect(r.blocks.at(-1).text).toContain('Escrito en otra sesión')
})

test('a git failure after the turn does not reject the hook', async ($, on) => {
  const w = world(on)
  turns(on)
  await w.start($)
  w.flags.failGit = true
  const r = await endTurn($, 'corto')
  expect(r.text).toBe('corto')
  expect(w.logs.some(l => l.includes('leer la rama tras el turno falló'))).toBe(true)
})

test('starting a session twice does not stack the refresh timer', async ($, on) => {
  const w = world(on)
  await w.start($)
  await w.start($)
  await w.clock.settle()
  w.state.invalidations = 0
  await w.clock.advance(60000)
  expect(w.state.invalidations).toBe(1)
})
