import { expect, test } from 'claude-code/testing'
import { ROOT, world } from './world.ts'

const BAND = { component: 'AbovePrompt', props: { hasSurvey: false, isWorking: false, maxRows: 10, bodyColumns: 100 } as any }
const PANE = { component: 'Pane', requestId: 'loose-ends', props: { title: 'Cuaderno', isFocused: true, bodyColumns: 60, placement: 'dock' } as any }
const file = JSON.stringify({ version: 1, items: [
  { id: 'a1', text: 'Test de canonical', priority: 'high', status: 'open', branch: 'main', createdAt: '2026-10-04T09:48:00.000Z' },
  { id: 'b2', text: 'Otra rama', priority: 'low', status: 'open', branch: 'feat/x', createdAt: '2026-10-04T09:00:00.000Z' },
] })

test('band: Chispa on desktop, face on terminal, counters for this branch', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: file } })
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  await w.start($)
  const desk = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...BAND })
  expect(await desk.find({ type: 'Svg' })).toBeDefined()
  expect((await desk.find({ key: 'open-pane' }))?.text).toBe('1 pendiente (1 urgente) · [Ver](file:///loose-ends/ver)')
  expect(await desk.find({ key: 'open-pane' })).toBeDefined()
  await desk.unmount()
  const term = await $.ui.mount({ plugin: 'loose-ends', surface: 'terminal', ...BAND })
  expect(await term.find({ type: 'Svg' })).toBeUndefined()
  await term.unmount()
})

test('pane buttons change the file', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: file } })
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  on('prompt.submit', ($: any, e: any) => ({ text: e.text }))
  await w.start($)
  const ui = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...PANE })
  expect(await ui.find({ key: 'queue-a1' })).toBeUndefined()
  await ui.press({ key: 'more-a1' })
  await ui.redraw()
  await ui.press({ key: 'queue-a1' })
  await w.clock.settle()
  expect(w.saved().find((i: any) => i.id === 'a1').status).toBe('queued')
  await ui.redraw()
  await ui.press({ key: 'more-a1' })
  await ui.redraw()
  await ui.press({ key: 'dismiss-a1' })
  await ui.redraw()
  expect(await ui.find({ key: 'reason-a1' })).toBeDefined()
  await ui.press({ key: 'done-a1' })
  await w.clock.settle()
  expect(w.saved().find((i: any) => i.id === 'a1')).toMatchObject({ status: 'done', closedBy: 'user' })
  await ui.redraw()
  expect(await ui.find({ key: 'reopen-a1' })).toBeUndefined()
  await ui.press({ key: 'toggle-done' })
  await ui.redraw()
  await ui.press({ key: 'reopen-a1' })
  await w.clock.settle()
  expect(w.saved().find((i: any) => i.id === 'a1').status).toBe('open')
  await ui.unmount()
})

test('Hazlo ahora submits a prompt and marks the item reminded', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: file } })
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  let sent = ''
  on('prompt.submit', ($: any, e: any) => { sent = e.text; return { text: e.text } })
  await w.start($)
  const ui = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...PANE })
  await ui.press({ key: 'now-a1' })
  await w.clock.settle()
  expect(sent).toContain('Resuelve este cabo suelto (a1)')
  expect(w.saved().find((i: any) => i.id === 'a1')).toMatchObject({ status: 'queued' })
  expect(w.saved().find((i: any) => i.id === 'a1').remindedAt).toBeTruthy()
  await ui.unmount()
})

test('the mobile surface draws no pane', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: file } })
  on('ui.render', () => ({ type: 'Text', children: ['engine pane'] }))
  await w.start($)
  const ui = await $.ui.mount({ plugin: 'loose-ends', surface: 'mobile', ...PANE })
  expect(await ui.find({ type: 'Text', text: /engine pane/ })).toBeDefined()
  expect(await ui.find({ key: 'queue-a1' })).toBeUndefined()
  await ui.unmount()
})

test('/pendientes opens the pane', async ($, on) => {
  const w = world(on)
  let opened = ''
  on('ui.open', ($: any, e: any) => { opened = e.id; return { value: { isPlaced: true } } })
  await w.start($)
  await $.command.run({ command: 'pendientes', args: '' })
  expect(opened).toBe('loose-ends')
})

test('Hazlo ahora does not submit when the file became unreadable', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: file } })
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  let sent = ''
  on('prompt.submit', ($: any, e: any) => { sent = e.text; return { text: e.text } })
  await w.start($)
  const ui = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...PANE })
  w.setRef(ROOT, '<<<<<<< HEAD\n{}\n=======\n>>>>>>> x\n')
  await ui.press({ key: 'now-a1' })
  await w.clock.settle()
  expect(sent).toBe('')
  await ui.unmount()
})

test('a failing write from a pane button is logged, not thrown', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: file } })
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  await w.start($)
  const ui = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...PANE })
  w.flags.failWrites = true
  await ui.press({ key: 'more-a1' })
  await ui.redraw()
  await ui.press({ key: 'queue-a1' })
  await w.clock.settle()
  expect(w.logs).toEqual([expect.stringContaining('falló')])
  await ui.unmount()
})

test('the discard picker closes once the item is resolved', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: file } })
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  await w.start($)
  const ui = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...PANE })
  await ui.press({ key: 'more-a1' })
  await ui.redraw()
  await ui.press({ key: 'dismiss-a1' })
  await ui.redraw()
  expect(await ui.find({ key: 'reason-a1' })).toBeDefined()
  await ui.press({ key: 'done-a1' })
  await w.clock.settle()
  await ui.redraw()
  await ui.press({ key: 'toggle-done' })
  await ui.redraw()
  await ui.press({ key: 'reopen-a1' })
  await w.clock.settle()
  await ui.redraw()
  expect(await ui.find({ key: 'reason-a1' })).toBeUndefined()
  await ui.unmount()
})

test('a throwing log inside a failed background action is swallowed', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: file } })
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  await w.start($)
  const ui = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...PANE })
  w.flags.failWrites = true
  w.flags.failLog = true
  await ui.press({ key: 'more-a1' })
  await ui.redraw()
  await ui.press({ key: 'queue-a1' })
  await w.clock.settle()
  await ui.unmount()
})

const two = JSON.stringify({ version: 1, items: [
  { id: 'a1', text: 'Test de canonical', priority: 'high', status: 'open', branch: 'main', createdAt: '2026-10-04T09:48:00.000Z', evidence: 'lo dejo fuera del alcance' },
  { id: 'c3', text: 'Otro cabo', priority: 'medium', status: 'open', branch: 'main', createdAt: '2026-10-04T09:50:00.000Z' },
] })

test('the priority buttons set the priority and keep the item expanded', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: two } })
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  await w.start($)
  const ui = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...PANE })
  await ui.press({ key: 'more-a1' })
  await ui.redraw()
  expect(await ui.find({ type: 'Text', text: '«lo dejo fuera del alcance»' })).toBeDefined()
  await ui.press({ key: 'prio-a1-low' })
  await w.clock.settle()
  await ui.redraw()
  expect(w.saved().find((i: any) => i.id === 'a1').priority).toBe('low')
  expect(await ui.find({ key: 'prio-a1-medium' })).toBeDefined()
  await ui.press({ key: 'prio-a1-high' })
  await w.clock.settle()
  expect(w.saved().find((i: any) => i.id === 'a1').priority).toBe('high')
  await ui.unmount()
})

test('only one item is expanded at a time and more toggles it', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: two } })
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  await w.start($)
  const ui = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...PANE })
  await ui.press({ key: 'more-a1' })
  await ui.redraw()
  expect(await ui.find({ key: 'queue-a1' })).toBeDefined()
  await ui.press({ key: 'more-c3' })
  await ui.redraw()
  expect(await ui.find({ key: 'queue-a1' })).toBeUndefined()
  expect(await ui.find({ key: 'queue-c3' })).toBeDefined()
  await ui.press({ key: 'more-c3' })
  await ui.redraw()
  expect(await ui.find({ key: 'queue-c3' })).toBeUndefined()
  await ui.unmount()
})

test('a new session starts with everything collapsed', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: two } })
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  await w.start($)
  const ui = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...PANE })
  await ui.press({ key: 'more-a1' })
  await ui.press({ key: 'done-c3' })
  await w.clock.settle()
  await ui.redraw()
  await ui.press({ key: 'toggle-done' })
  await ui.redraw()
  expect(await ui.find({ key: 'queue-a1' })).toBeDefined()
  expect(await ui.find({ key: 'reopen-c3' })).toBeDefined()
  await w.start($)
  await ui.redraw()
  expect(await ui.find({ key: 'queue-a1' })).toBeUndefined()
  expect(await ui.find({ key: 'reopen-c3' })).toBeUndefined()
  await ui.unmount()
})

test('resolving the expanded item collapses it', async ($, on) => {
  const w = world(on, {}, { refs: { [ROOT]: two } })
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  await w.start($)
  const ui = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...PANE })
  await ui.press({ key: 'more-a1' })
  await ui.redraw()
  await ui.press({ key: 'queue-a1' })
  await w.clock.settle()
  await ui.redraw()
  expect(await ui.find({ key: 'queue-a1' })).toBeUndefined()
  await ui.unmount()
})

test('band: with nothing to report only Chispa is drawn', async ($, on) => {
  const w = world(on)
  on('ui.render', () => ({ type: 'Box', props: { children: [] } }))
  await w.start($)
  const band = await $.ui.mount({ plugin: 'loose-ends', surface: 'desktop', ...BAND })
  expect(await band.find({ type: 'Svg' })).toBeDefined()
  expect(await band.find({ type: 'Text' })).toBeUndefined()
  expect(await band.find({ key: 'open-pane' })).toBeUndefined()
  await band.unmount()
})
